Create Table: CREATE TABLE `product_details` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `product_id` int(11) DEFAULT NULL,
  `body` text,
  `shipping_info` text,
  `returns_info` text,
  `meta_description` text,
  `keywords` varchar(255) DEFAULT NULL,
  `body_locked` tinyint(1) DEFAULT NULL,
  `lock_version` int(11) DEFAULT '0',
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  `created_by_id` int(11) DEFAULT NULL,
  `updated_by_id` int(11) DEFAULT NULL,
  `sizes` text NOT NULL,
  `materials` text NOT NULL,
  `variations_available` text NOT NULL,
  `other_information` text NOT NULL,
  `seasonal_information` text,
  `curation_bespoke` tinyint(1) DEFAULT '0',
  `bespoke_expires_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `product_details_ibfk_product_id` (`product_id`),
  KEY `product_details_ibfk_created_by_id` (`created_by_id`),
  KEY `product_details_ibfk_updated_by_id` (`updated_by_id`),
  CONSTRAINT `product_details_ibfk_created_by_id` FOREIGN KEY (`created_by_id`) REFERENCES `users` (`id`),
  CONSTRAINT `product_details_ibfk_product_id` FOREIGN KEY (`product_id`) REFERENCES `products` (`id`),
  CONSTRAINT `product_details_ibfk_updated_by_id` FOREIGN KEY (`updated_by_id`) REFERENCES `users` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=577249 DEFAULT CHARSET=utf8