CREATE TABLE `partners` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(255) DEFAULT NULL,
  `shortcode` varchar(255) DEFAULT NULL,
  `charges_vat` tinyint(1) DEFAULT NULL,
  `registered_company` tinyint(1) DEFAULT NULL,
  `vat_number` varchar(255) DEFAULT NULL,
  `company_registration_number` varchar(255) DEFAULT NULL,
  `commission_rate` decimal(4,2) DEFAULT NULL,
  `logo_file_name` varchar(255) DEFAULT NULL,
  `logo_content_type` varchar(255) DEFAULT NULL,
  `brand_file_name` varchar(255) DEFAULT NULL,
  `brand_content_type` varchar(255) DEFAULT NULL,
  `logo_file_size` int(11) DEFAULT NULL,
  `brand_file_size` int(11) DEFAULT NULL,
  `logo_updated_at` datetime DEFAULT NULL,
  `brand_updated_at` datetime DEFAULT NULL,
  `short_description` text,
  `long_description` text,
  `terms_info` text,
  `returns_info` text,
  `delivery_info` text,
  `meta_description` text,
  `seasonal_shipping_info` text,
  `xmas_last_order_date` date DEFAULT NULL,
  `default_delivery_size_id` int(11) DEFAULT NULL,
  `default_delivery_class_id` int(11) DEFAULT NULL,
  `default_delivery_time_id` int(11) DEFAULT NULL,
  `express_delivery_active` tinyint(1) DEFAULT NULL,
  `international_delivery_active` tinyint(1) DEFAULT NULL,
  `allows_gift_wrap` tinyint(1) DEFAULT NULL,
  `allows_gift_message` tinyint(1) DEFAULT NULL,
  `virtual_bank_account_id` int(11) DEFAULT NULL,
  `current_bank_account_id` int(11) DEFAULT NULL,
  `trading_address_id` int(11) DEFAULT NULL,
  `correspondence_address_id` int(11) DEFAULT NULL,
  `company_address_id` int(11) DEFAULT NULL,
  `returns_address_id` int(11) DEFAULT NULL,
  `contact_name` varchar(255) DEFAULT NULL,
  `main_email` varchar(255) DEFAULT NULL,
  `order_contact_name` varchar(255) DEFAULT NULL,
  `order_email` varchar(255) DEFAULT NULL,
  `fulfillment_house_contact_name` varchar(255) DEFAULT NULL,
  `fulfillment_house_email` varchar(255) DEFAULT NULL,
  `accounting_contact_name` varchar(255) DEFAULT NULL,
  `accounting_email` varchar(255) DEFAULT NULL,
  `press_contact_name` varchar(255) DEFAULT NULL,
  `press_email` varchar(255) DEFAULT NULL,
  `customer_service_contact_name` varchar(255) DEFAULT NULL,
  `customer_service_email` varchar(255) DEFAULT NULL,
  `telephone` varchar(255) DEFAULT NULL,
  `telephone_2` varchar(255) DEFAULT NULL,
  `telephone_3` varchar(255) DEFAULT NULL,
  `website_url` varchar(255) DEFAULT NULL,
  `state` varchar(255) DEFAULT NULL,
  `payment_code` varchar(255) DEFAULT NULL,
  `joining_fee_net` decimal(14,6) DEFAULT NULL,
  `joined_at` datetime DEFAULT NULL,
  `next_contact_date` datetime DEFAULT NULL,
  `trading_standards_confirmed` tinyint(1) DEFAULT NULL,
  `signup_first_payment_net` decimal(14,6) DEFAULT NULL,
  `signup_vat_rate` decimal(4,2) DEFAULT NULL,
  `subscription_fee` decimal(14,6) DEFAULT NULL,
  `signup_final_payment_due_date` datetime DEFAULT NULL,
  `subscription_end_date` datetime DEFAULT NULL,
  `subscription_length` int(11) DEFAULT NULL,
  `renewal_commission_rate` decimal(4,2) DEFAULT NULL,
  `renewal_vat_rate` decimal(4,2) DEFAULT NULL,
  `renewal_key` varchar(255) DEFAULT NULL,
  `renewal_status` varchar(255) DEFAULT NULL,
  `press_comments` text,
  `partner_comments` text,
  `customer_comments` text,
  `notes_admin` text,
  `notes_urgent` text,
  `notes_press` text,
  `notes_sales` text,
  `notes_production` text,
  `banding_package` varchar(15) DEFAULT NULL,
  `banding_potential` varchar(1) DEFAULT NULL,
  `banding_status` varchar(15) DEFAULT NULL,
  `lock_version` int(11) DEFAULT '0',
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  `updated_by_id` int(11) DEFAULT NULL,
  `created_by_id` int(11) DEFAULT NULL,
  `holiday_from_date` datetime DEFAULT NULL,
  `holiday_return_date` datetime DEFAULT NULL,
  `last_dispatch_pack_sent_at` datetime DEFAULT NULL,
  `free_shipping_over_limit` tinyint(1) DEFAULT NULL,
  `delta` tinyint(1) NOT NULL DEFAULT '0',
  `source` varchar(255) DEFAULT NULL,
  `accepted_at` datetime DEFAULT NULL,
  `accepted_by_id` int(11) DEFAULT NULL,
  `approved_at` datetime DEFAULT NULL,
  `approved_by_id` int(11) DEFAULT NULL,
  `declined_at` datetime DEFAULT NULL,
  `declined_by_id` int(11) DEFAULT NULL,
  `activated_at` datetime DEFAULT NULL,
  `activated_by_id` int(11) DEFAULT NULL,
  `closed_at` datetime DEFAULT NULL,
  `closed_by_id` int(11) DEFAULT NULL,
  `applied_at` datetime DEFAULT NULL,
  `confirmed_at` datetime DEFAULT NULL,
  `paid_at` datetime DEFAULT NULL,
  `signup_payment_method` varchar(255) DEFAULT NULL,
  `signup_invoice_id` int(11) DEFAULT NULL,
  `payable` tinyint(1) DEFAULT NULL,
  `partner_terms_accepted` tinyint(1) DEFAULT NULL,
  `number_of_available_products_allowed` int(11) DEFAULT NULL,
  `activation_support_enquiry_id` int(11) DEFAULT NULL,
  `xmas_last_order_date_confirmed` tinyint(1) DEFAULT NULL,
  `decline_reason` varchar(50) DEFAULT NULL,
  `other_decline_reason` text,
  `company_status` varchar(255) DEFAULT NULL,
  `trading_products_sold` text,
  `company_registration_name` varchar(255) DEFAULT NULL,
  `country_of_registration` varchar(255) DEFAULT NULL,
  `xmas_last_order_date_express` date DEFAULT NULL,
  `one_to_watch` tinyint(1) NOT NULL DEFAULT '0',
  `rising_star` tinyint(1) NOT NULL DEFAULT '0',
  `account_manager_id` int(11) DEFAULT NULL,
  `telephone_alpha2` varchar(255) DEFAULT NULL,
  `telephone_2_alpha2` varchar(255) DEFAULT NULL,
  `telephone_3_alpha2` varchar(255) DEFAULT NULL,
  `requested_activation_at` datetime DEFAULT NULL,
  `partner_team_id` int(11) DEFAULT NULL,
  `social_media_profiles` text,
  `works_sunday` tinyint(1) NOT NULL DEFAULT '1',
  `kyc_completed` tinyint(1) DEFAULT '0',
  `kyc_completed_at` datetime DEFAULT NULL,
  `kyc_completed_by_id` int(11) DEFAULT NULL,
  `logo_uri` varchar(255) DEFAULT NULL,
  `brand_uri` varchar(255) DEFAULT NULL,
  `delivery_service_from` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `partners_ibfk_default_delivery_size_id` (`default_delivery_size_id`),
  KEY `partners_ibfk_default_delivery_class_id` (`default_delivery_class_id`),
  KEY `partners_ibfk_default_delivery_time_id` (`default_delivery_time_id`),
  KEY `partners_ibfk_virtual_bank_account_id` (`virtual_bank_account_id`),
  KEY `partners_ibfk_current_bank_account_id` (`current_bank_account_id`),
  KEY `partners_ibfk_main_address_id` (`trading_address_id`),
  KEY `partners_ibfk_correspondence_address_id` (`correspondence_address_id`),
  KEY `partners_ibfk_company_address_id` (`company_address_id`),
  KEY `partners_ibfk_returns_address_id` (`returns_address_id`),
  KEY `partners_ibfk_updated_by_id` (`updated_by_id`),
  KEY `partners_ibfk_created_by_id` (`created_by_id`),
  KEY `partners_ibfk_accepted_by_id` (`accepted_by_id`),
  KEY `partners_ibfk_approved_by_id` (`approved_by_id`),
  KEY `partners_ibfk_declined_by_id` (`declined_by_id`),
  KEY `partners_ibfk_activated_by_id` (`activated_by_id`),
  KEY `partners_ibfk_closed_by_id` (`closed_by_id`),
  KEY `partners_ibfk_signup_invoice_id` (`signup_invoice_id`),
  KEY `index_partners_on_state` (`state`),
  KEY `partners_ibfk_activation_support_enquiry_id` (`activation_support_enquiry_id`),
  KEY `index_partners_on_next_contact_date` (`next_contact_date`),
  KEY `index_partners_on_created_at` (`created_at`),
  KEY `index_partners_on_xmas_last_order_date_confirmed` (`xmas_last_order_date_confirmed`),
  KEY `index_partners_on_shortcode` (`shortcode`) USING BTREE,
  KEY `partners_by_name` (`name`),
  CONSTRAINT `partners_ibfk_accepted_by_id` FOREIGN KEY (`accepted_by_id`) REFERENCES `users` (`id`),
  CONSTRAINT `partners_ibfk_activated_by_id` FOREIGN KEY (`activated_by_id`) REFERENCES `users` (`id`),
  CONSTRAINT `partners_ibfk_activation_support_enquiry_id` FOREIGN KEY (`activation_support_enquiry_id`) REFERENCES `support_enquiries` (`id`),
  CONSTRAINT `partners_ibfk_approved_by_id` FOREIGN KEY (`approved_by_id`) REFERENCES `users` (`id`),
  CONSTRAINT `partners_ibfk_closed_by_id` FOREIGN KEY (`closed_by_id`) REFERENCES `users` (`id`),
  CONSTRAINT `partners_ibfk_company_address_id` FOREIGN KEY (`company_address_id`) REFERENCES `addresses` (`id`),
  CONSTRAINT `partners_ibfk_correspondence_address_id` FOREIGN KEY (`correspondence_address_id`) REFERENCES `addresses` (`id`),
  CONSTRAINT `partners_ibfk_created_by_id` FOREIGN KEY (`created_by_id`) REFERENCES `users` (`id`),
  CONSTRAINT `partners_ibfk_current_bank_account_id` FOREIGN KEY (`current_bank_account_id`) REFERENCES `bank_accounts` (`id`),
  CONSTRAINT `partners_ibfk_declined_by_id` FOREIGN KEY (`declined_by_id`) REFERENCES `users` (`id`),
  CONSTRAINT `partners_ibfk_default_delivery_class_id` FOREIGN KEY (`default_delivery_class_id`) REFERENCES `delivery_classes` (`id`),
  CONSTRAINT `partners_ibfk_default_delivery_size_id` FOREIGN KEY (`default_delivery_size_id`) REFERENCES `delivery_sizes` (`id`),
  CONSTRAINT `partners_ibfk_default_delivery_time_id` FOREIGN KEY (`default_delivery_time_id`) REFERENCES `delivery_times` (`id`),
  CONSTRAINT `partners_ibfk_returns_address_id` FOREIGN KEY (`returns_address_id`) REFERENCES `addresses` (`id`),
  CONSTRAINT `partners_ibfk_signup_invoice_id` FOREIGN KEY (`signup_invoice_id`) REFERENCES `financial_documents` (`id`),
  CONSTRAINT `partners_ibfk_updated_by_id` FOREIGN KEY (`updated_by_id`) REFERENCES `users` (`id`),
  CONSTRAINT `partners_ibfk_virtual_bank_account_id` FOREIGN KEY (`virtual_bank_account_id`) REFERENCES `bank_accounts` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=68323 DEFAULT CHARSET=utf8