Create Table: CREATE TABLE `product_options` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `product_id` int(11) DEFAULT NULL,
  `product_option_category_id` int(11) DEFAULT NULL,
  `type_attribute_id` int(11) DEFAULT NULL,
  `name` varchar(255) DEFAULT NULL,
  `definition` varchar(255) DEFAULT NULL,
  `allowed_case` varchar(255) NOT NULL DEFAULT 'not applicable',
  `required` tinyint(1) DEFAULT NULL,
  `enabled` tinyint(1) DEFAULT NULL,
  `stockable` tinyint(1) DEFAULT NULL,
  `validate_maximum` int(11) DEFAULT NULL,
  `validate_minimum` int(11) DEFAULT NULL,
  `position` int(11) DEFAULT NULL,
  `deleted_at` datetime DEFAULT NULL,
  `lock_version` int(11) DEFAULT '0',
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  `created_by_id` int(11) DEFAULT NULL,
  `updated_by_id` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `product_options_ibfk_created_by_id` (`created_by_id`),
  KEY `product_options_ibfk_updated_by_id` (`updated_by_id`),
  KEY `index_product_options_on_product_id_and_deleted_at` (`product_id`,`deleted_at`),
  KEY `index_product_options_on_updated_at` (`updated_at`),
  KEY `product_options_ibfk_product_option_category_id` (`product_option_category_id`),
  CONSTRAINT `product_options_ibfk_created_by_id` FOREIGN KEY (`created_by_id`) REFERENCES `users` (`id`),
  CONSTRAINT `product_options_ibfk_product_id` FOREIGN KEY (`product_id`) REFERENCES `products` (`id`),
  CONSTRAINT `product_options_ibfk_product_option_category_id` FOREIGN KEY (`product_option_category_id`) REFERENCES `product_option_categories` (`id`),
  CONSTRAINT `product_options_ibfk_updated_by_id` FOREIGN KEY (`updated_by_id`) REFERENCES `users` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=2280844 DEFAULT CHARSET=utf8