Create Table: CREATE TABLE `product_images` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `product_id` int(11) DEFAULT NULL,
  `image_file_name` varchar(255) DEFAULT NULL,
  `image_content_type` varchar(255) DEFAULT NULL,
  `image_file_size` int(11) DEFAULT NULL,
  `original_image_file_name` varchar(255) DEFAULT NULL,
  `original_image_content_type` varchar(255) DEFAULT NULL,
  `original_image_file_size` int(11) DEFAULT NULL,
  `original_image_width` int(11) DEFAULT NULL,
  `original_image_height` int(11) DEFAULT NULL,
  `preview_image_file_name` varchar(255) DEFAULT NULL,
  `preview_image_content_type` varchar(255) DEFAULT NULL,
  `preview_image_file_size` int(11) DEFAULT NULL,
  `crop_width` int(11) DEFAULT NULL,
  `crop_height` int(11) DEFAULT NULL,
  `crop_left` int(11) DEFAULT NULL,
  `crop_top` int(11) DEFAULT NULL,
  `preview_crop_width` int(11) DEFAULT NULL,
  `preview_crop_height` int(11) DEFAULT NULL,
  `preview_crop_left` int(11) DEFAULT NULL,
  `preview_crop_top` int(11) DEFAULT NULL,
  `position` int(11) DEFAULT NULL,
  `visible` tinyint(1) DEFAULT NULL,
  `lock_version` int(11) DEFAULT '0',
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  `updated_by_id` int(11) DEFAULT NULL,
  `created_by_id` int(11) DEFAULT NULL,
  `alt` varchar(255) DEFAULT NULL,
  `gravity` varchar(10) DEFAULT NULL,
  `system_folder` varchar(255) DEFAULT NULL,
  `original_image_uri` varchar(255) DEFAULT NULL,
  `image_uri` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `product_images_ibfk_product_id` (`product_id`),
  KEY `product_images_ibfk_updated_by_id` (`updated_by_id`),
  KEY `product_images_ibfk_created_by_id` (`created_by_id`),
  CONSTRAINT `product_images_ibfk_created_by_id` FOREIGN KEY (`created_by_id`) REFERENCES `users` (`id`),
  CONSTRAINT `product_images_ibfk_product_id` FOREIGN KEY (`product_id`) REFERENCES `products` (`id`),
  CONSTRAINT `product_images_ibfk_updated_by_id` FOREIGN KEY (`updated_by_id`) REFERENCES `users` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=2981854 DEFAULT CHARSET=utf8