Create Table: CREATE TABLE `users` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `partner_id` int(11) DEFAULT NULL,
  `title` varchar(255) DEFAULT NULL,
  `first_name` varchar(255) DEFAULT NULL,
  `last_name` varchar(255) DEFAULT NULL,
  `telephone` varchar(255) DEFAULT NULL,
  `email` varchar(255) DEFAULT NULL,
  `source` varchar(255) DEFAULT NULL,
  `encrypted_password` varchar(40) DEFAULT NULL,
  `encrypted_password_scrypt` varchar(255) DEFAULT NULL,
  `salt` varchar(40) DEFAULT NULL,
  `email_confirmed` tinyint(1) NOT NULL DEFAULT '0',
  `enabled` tinyint(1) DEFAULT NULL,
  `terms_read` tinyint(1) DEFAULT NULL,
  `temporary` tinyint(1) DEFAULT NULL,
  `default_billing_address_id` int(11) DEFAULT NULL,
  `default_shipping_address_id` int(11) DEFAULT NULL,
  `temporary_password` varchar(255) DEFAULT NULL,
  `remember_key` varchar(255) DEFAULT NULL,
  `lost_password_key` varchar(255) DEFAULT NULL,
  `lock_version` int(11) DEFAULT '0',
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  `updated_by_id` int(11) DEFAULT NULL,
  `created_by_id` int(11) DEFAULT NULL,
  `delta` tinyint(1) NOT NULL DEFAULT '0',
  `generated_password` varchar(255) DEFAULT NULL,
  `bank_account_id` int(11) DEFAULT NULL,
  `signup_source` varchar(255) DEFAULT NULL,
  `telephone_alpha2` varchar(255) DEFAULT NULL,
  `spammer` tinyint(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  KEY `users_ibfk_partner_id` (`partner_id`),
  KEY `users_ibfk_default_billing_address_id` (`default_billing_address_id`),
  KEY `users_ibfk_default_shipping_address_id` (`default_shipping_address_id`),
  KEY `users_ibfk_updated_by_id` (`updated_by_id`),
  KEY `users_ibfk_created_by_id` (`created_by_id`),
  KEY `index_users_on_email` (`email`),
  KEY `index_users_on_created_at` (`created_at`),
  KEY `index_users_on_delta` (`delta`) USING BTREE,
  KEY `users_ibfk_bank_account_id` (`bank_account_id`),
  KEY `index_users_on_last_name` (`last_name`),
  CONSTRAINT `users_ibfk_bank_account_id` FOREIGN KEY (`bank_account_id`) REFERENCES `bank_accounts` (`id`),
  CONSTRAINT `users_ibfk_created_by_id` FOREIGN KEY (`created_by_id`) REFERENCES `users` (`id`),
  CONSTRAINT `users_ibfk_default_billing_address_id` FOREIGN KEY (`default_billing_address_id`) REFERENCES `addresses` (`id`),
  CONSTRAINT `users_ibfk_default_shipping_address_id` FOREIGN KEY (`default_shipping_address_id`) REFERENCES `addresses` (`id`),
  CONSTRAINT `users_ibfk_partner_id` FOREIGN KEY (`partner_id`) REFERENCES `partners` (`id`),
  CONSTRAINT `users_ibfk_updated_by_id` FOREIGN KEY (`updated_by_id`) REFERENCES `users` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=82635 DEFAULT CHARSET=utf8